spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-202404b
    username: postgres
    password: postgres
  # sql:
  #   init:
  #     mode: always
  #     schema-locations: classpath:schema-postgresql.sql
  jpa:
    hibernate:
      ddl-auto: create
    # defer-datasource-initialization: true

jwt:
  expirationDays: 90
  secretKey: f5c760c5-bb7f-4910-8fd4-bc6892112512
