spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-202404b
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql
    jpa:
      defer-datasource-initialization: true