spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-202404b
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: quymao08101999@gmail.com
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
        auth: true
  jpa:
    hibernate:
      ddl-auto: create
    # defer-datasource-initialization: true

jwt:
  expirationDays: 90
  secretKey: f5c760c5-bb7f-4910-8fd4-bc6892112512
